import {readFile} from 'node:fs/promises';
import {services} from './lib/db.mjs';
import {seoPage,escape as e,SITE} from './lib/seo-page.mjs';
const data=async name=>JSON.parse(await readFile(new URL('../../public/data/'+name+'.json',import.meta.url),'utf8').catch(()=>readFile('public/data/'+name+'.json','utf8')));
const html=(body,status=200)=>new Response(body,{status,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':status===200?'public, max-age=0, s-maxage=3600':'no-store'}});
async function records(kind){const {db}=services();let query=db.collection(kind);if(kind==='news')query=query.where('published','==',true);const snap=await query.limit(1000).get();return snap.docs.map(doc=>({id:doc.id,...doc.data()}))}
export default async function(request){const url=new URL(request.url),path=url.searchParams.get('path')||url.pathname;try{
 if(path==='/sitemap.xml'){const paths=await data('seo-paths');try{for(const kind of ['news','builds'])for(const row of await records(kind))paths.push('/guide/'+(kind==='builds'?'build':'news')+'/'+encodeURIComponent(row.id)+'/')}catch{}return new Response('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+paths.map(path=>`<url><loc>${e(SITE+path)}</loc></url>`).join('')+'</urlset>',{headers:{'Content-Type':'application/xml; charset=utf-8','Cache-Control':'public, max-age=0, s-maxage=3600'}})}
 const match=path.match(/^\/guide\/(builds|build|news)\/?([^/]*)\/?$/);if(!match)return html('Sahifa topilmadi.',404);const section=match[1],kind=section==='news'?'news':'builds',id=match[2];
 if(!id){const rows=(await records(kind)).sort((a,b)=>String(b.sourcePublishedAt||b.createdAt||'').localeCompare(String(a.sourcePublishedAt||a.createdAt||'')));return html(seoPage(kind==='news'?'MLBB yangiliklari o‘zbekcha':'MLBB buildlar — buyumlar to‘plami',kind==='news'?'NEXUS MLBB yangiliklari va manbali o‘zbekcha qisqa izohlar.':'MLBB herolari uchun community va AI buildlar.','/guide/'+section+'/',`<div class="stack">${rows.map(row=>`<a class="card" href="/guide/${kind==='news'?'news':'build'}/${encodeURIComponent(row.id)}/"><h2>${e(row.title||row.name)}</h2><p>${e(row.summary||row.description||'')}</p></a>`).join('')||'<p>Hozircha yozuvlar yo‘q.</p>'}</div>`))}
 if(!/^[a-zA-Z0-9_-]{1,128}$/.test(id))return html('Sahifa topilmadi.',404);const snapshot=await services().db.collection(kind).doc(id).get();if(!snapshot.exists||(kind==='news'&&!snapshot.data().published))return html('Sahifa topilmadi.',404);const row=snapshot.data();let content;
 if(kind==='news')content=`<p>${e(row.summary)}</p><p>${e(row.category)} · ${e(row.sourcePublishedAt?.slice(0,10))}</p>${/^https:\/\//.test(row.sourceUrl||'')?`<a href="${e(row.sourceUrl)}" rel="noopener noreferrer">${e(row.sourceName||'Yangilik manbasi')}</a>`:''}<p><a class="button" href="/#/news/${e(id)}">Saytda yangilikni ochish</a></p>`;
 else{const items=await data('items'),heroes=await data('heroes'),hero=heroes.find(h=>h.id===row.hero);content=`<p>Hero: <a href="/guide/heroes/${e(row.hero)}/">${e(hero?.name||row.hero)}</a></p><div class="equipment-strip">${(row.items||[]).map(id=>{const item=items.find(i=>i.id===id);return item?`<article><img src="${e(item.image)}" alt="${e(item.name)}" width="64" height="64"><h3>${e(item.name)}</h3><p>${e(item.description)}</p></article>`:''}).join('')}</div><p>Emblem: ${e(row.emblem)} · Spell: ${e(row.spell)}</p><p>${e(row.description)}</p><a class="button" href="/#/build/${e(id)}">Buildni saytda ochish</a><p>Tavsiya g‘alaba kafolati emas. Patch va raqib tarkibiga qarab moslang.</p>`}
 return html(seoPage(row.title||row.name,String(row.summary||row.description||'MLBB NEXUS qo‘llanmasi').slice(0,160),'/guide/'+(kind==='news'?'news':'build')+'/'+id+'/',content));
 }catch{return html('Ma’lumotni hozir yuklab bo‘lmadi. Keyinroq qayta oching.',503)}}
