import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
const root=path.resolve(import.meta.dirname,'..');process.chdir(root);
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)])}
for(const p of [...walk('public/js'),...walk('netlify'),...walk('scripts')].filter(p=>/\.(mjs|js)$/.test(p))){const r=spawnSync(process.execPath,['--check',p],{encoding:'utf8'});assert.equal(r.status,0,`${p}\n${r.stderr}`)}
const bank=JSON.parse(fs.readFileSync('public/data/quiz-data.json'));assert.equal(bank.length,1000);assert.equal(new Set(bank.map(q=>q.question.trim().toLowerCase())).size,1000);assert.equal(new Set(bank.map(q=>q.id)).size,1000);for(const [d,n] of Object.entries({easy:400,medium:400,hard:200}))assert.equal(bank.filter(q=>q.difficulty===d).length,n);for(const q of bank){assert.equal(q.options.length,4);assert.equal(new Set(q.options).size,4);assert.ok(Number.isInteger(q.correct)&&q.correct>=0&&q.correct<4);assert.ok(q.explanation&&q.category&&q.question)}
const heroes=JSON.parse(fs.readFileSync('public/data/heroes.json'));assert.equal(new Set(heroes.map(h=>h.id)).size,heroes.length);for(const h of heroes){if(h.image?.startsWith('/'))assert.ok(fs.existsSync('public'+h.image));for(const c of [...(h.counters||[]),...(h.allies||[])])assert.ok(heroes.some(h=>h.id===c),c)}
for(const name of ['index.html','style.css','js/app.js','sw.js','manifest.webmanifest'])assert.ok(fs.existsSync('public/'+name));
const html=fs.readFileSync('public/index.html','utf8');for(const m of html.matchAll(/(?:src|href)="(\/[^"#]+)"/g))assert.ok(fs.existsSync('public'+m[1]),m[1]);
const scripts=walk('public').filter(p=>/\.(js|html|json)$/.test(p));for(const p of scripts){const content=fs.readFileSync(p,'utf8');assert.ok(!content.includes('BEGIN PRIVATE KEY'),p);assert.ok(!/sk-[A-Za-z0-9]{20,}/.test(content),p)}
const response=await (await import('../netlify/functions/api.mjs')).default(new Request('https://nexus.example/api/health'));assert.equal(response.status,200);const health=await response.json();assert.equal(typeof health.configured,'boolean');const unauthorized=await (await import('../netlify/functions/api.mjs')).default(new Request('https://nexus.example/api/save',{method:'POST',body:'{}'}));assert.equal(unauthorized.status,401);
const linked=spawnSync(process.execPath,['--experimental-vm-modules','scripts/check-imports.mjs'],{encoding:'utf8'});assert.equal(linked.status,0,linked.stderr);
console.log(`OK: ${heroes.length} heroes; 1000 questions (400/400/200); JS syntax; module exports; assets; unauthenticated-write rejection.`);
