import {glossary} from '../public/js/glossary-data.js';
import fs from 'node:fs/promises';
import {seoPage,escape as e,SITE} from '../netlify/functions/lib/seo-page.mjs';
import {emblemGuides,emblemNamesUz,talentGuides,itemNamesUz,equipmentImageSources} from '../public/js/equipment-data.js';
const heroes=JSON.parse(await fs.readFile('public/data/heroes.json','utf8')),items=JSON.parse(await fs.readFile('public/data/items.json','utf8'));
const images=JSON.parse(await fs.readFile('public/data/equipment-images.json','utf8').catch(()=>'{}'));
const icon=name=>`<img src="${e(images[name]||equipmentImageSources[name])}" alt="${e(name)}" width="64" height="64" loading="lazy">`;
const links=heroes.map(h=>`<a class="card" href="/guide/heroes/${e(h.id)}/"><img src="${e(h.image)}" alt="${e(h.name)}" width="80" height="80" loading="lazy"><h2>${e(h.name)}</h2><p>${e(h.role)} · ${e(h.lane)}</p></a>`).join('');
async function write(path,title,description,body){await fs.mkdir('public'+path,{recursive:true});await fs.writeFile('public'+path+'index.html',seoPage(title,description,path,body))}
await write('/guide/','MLBB o‘zbekcha qo‘llanma','MLBB herolari, passive, counter, buyumlar, emblemlar va buildlar haqida o‘zbekcha NEXUS qo‘llanmasi.',`<p>Build — 6 ta buyum to‘plami. Emblem — qo‘shimcha atributlar tizimi. Passive — shart bajarilganda avtomatik ishlaydigan qobiliyat.</p><p><a href="/guide/training/">O‘zbekcha mashq rejasi</a></p><p><a href="/guide/glossary/">O‘zbekcha MLBB lug‘ati</a></p><p>Har bir hero sahifasida passive izohi va manbali counterlar bor.</p><div class="grid">${links}</div>`);
await write('/guide/items/','MLBB buyumlari — o‘zbekcha item izohlari','50 ta MLBB buyumining rasmlari, inglizcha va o‘zbekcha nom ma’nosi, nima qilishi va qachon olinishi.',`<p>O‘zbekcha nomlar nom ma’nosining tarjimasi; o‘yindagi rasmiy nomlar inglizcha qoladi. Build uchun buyumlarni vaziyatga mos tanlang.</p><div class="grid two mobile-one">${items.map(i=>`<article class="card"><img src="${e(i.image)}" alt="${e(i.name)}" width="80" height="80" loading="lazy"><h2>${e(i.name)} — ${e(itemNamesUz[i.id])}</h2><p>${e(i.description)}</p><h3>Qachon olinadi?</h3><p>${e(i.when)}</p></article>`).join('')}</div><p>Manba: <a href="https://mlbbdex.com/items">MLBBDex</a>. Patch bilan effektlar o‘zgarishi mumkin.</p>`);
await write('/guide/emblems/','MLBB emblemlari va talentlar — o‘zbekcha','7 ta MLBB emblem va talent vazifalari o‘zbek tilida.',`<div class="grid two mobile-one">${Object.entries(emblemGuides).map(([name,text])=>`<article class="card">${icon(name)}<h2>${e(name)} — ${e(emblemNamesUz[name])}</h2><p>${e(text)}</p></article>`).join('')}</div><h2>Talentlar</h2>${Object.entries(talentGuides).map(([name,text])=>`<section class="card">${icon(name)}<h3>${e(name)}</h3><p>${e(text)}</p></section>`).join('')}<p>Emblem atributlarni, talentlar alohida effektlarni beradi. Hero va raqib tarkibiga moslang.</p>`);
for(const h of heroes){const description=`${h.name} passive va counterlari o‘zbekcha. ${h.role}, ${h.lane}.`;await write('/guide/heroes/'+h.id+'/',h.name+' — passive, counter va build',description,`<img src="${e(h.image)}" alt="${e(h.name)} MLBB hero" width="160" height="160"><p>${e(h.role)} · ${e(h.lane)} · ${e(h.specialty)}</p><h2>Passive: ${e(h.passive)}</h2><p>${e(h.passiveGuide)}</p><p><a href="${e(h.passiveSource)}" rel="noopener noreferrer">Passive manbasi</a> · MLBB Wiki orqali MLBBDex, CC BY-SA.</p><h2>${e(h.name)}ga qarshi counter herolar</h2><ul>${(h.counters||[]).map(id=>{const c=heroes.find(x=>x.id===id);return c?`<li><a href="/guide/heroes/${e(id)}/">${e(c.name)}</a></li>`:''}).join('')}</ul><p><a href="https://mlbbhub.com/matchups">Counter manbasi: MLBBHub</a>. Ma’lumot olingan: ${e(h.counterUpdatedAt?.slice(0,10))}. G‘alaba kafolatlanmaydi.</p><h2>Build va skilllar</h2><p>Buildni hero vazifasi, damage turi va raqib himoyasiga moslang.</p><a class="button" href="/#/hero/${e(h.id)}">${e(h.name)}ning to‘liq sahifasi va buildlari</a><p>Patch o‘zgarganda skill va item tavsifini o‘yinda tekshiring.</p>`)}
await write('/guide/training/','MLBB mashq rejasi — Aamon va Alucard','MLBB herolari uchun o‘zbekcha passive, skill va xarita mashqlari.',`<p>Practice’da passive shartlarini sinang, skilllar orasida basic attack ishlating, xavfsiz chiqish va objective vaqtini mashq qiling.</p><p>Natijalarni o‘zingiz belgilaysiz.</p><a href="/#/training/aamon">Aamon mashq rejasi</a><p><a href="/#/training/alucard">Alucard mashq rejasi</a></p>`);
await write('/guide/glossary/','O‘zbekcha MLBB lug‘ati — gank, zoning, freeze va boshqa atamalar','MLBB atamalari o‘zbekcha: gank, zoning, freeze, invade, CC, build va xarita tushunchalari. Sodda izohlar va misollar.',`<p>Izohlar va misollar NEXUS tomonidan yozilgan. Aniq skill va item effektlarini o‘yinda tekshiring.</p><a href="/#/glossary">Qidiruvli lug‘atni ochish</a>${glossary.map(row=>`<article class="card"><h2>${e(row.term)} — ${e(row.uz)}</h2><p>${e(row.definition)}</p><h3>Misol</h3><p>${e(row.example)}</p></article>`).join('')}`);
const paths=['/guide/glossary/','/guide/training/','/','/guide/','/guide/items/','/guide/emblems/','/guide/builds/','/guide/news/',...heroes.map(h=>'/guide/heroes/'+h.id+'/')];await fs.writeFile('public/data/seo-paths.json',JSON.stringify(paths));await fs.writeFile('public/robots.txt',`User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /.netlify/\nSitemap: ${SITE}/sitemap.xml\n`);
console.log(`SEO: ${heroes.length} hero pages, item/emblem guides and crawlable links generated.`);
